add host as input argument for server
PrefectHQ/marvin pull request #347
Opened 2023-06-07 21:56 UTC by jicuss

would like to add host input argument to similar to the port argument below
marvin server start --port 8000

2023-06-07 22:07 UTC, zzstoatzz requested changes
thanks for the PR @jicuss 😄 

just one comment about the default value of the new typer option

2023-06-07 22:07 UTC, zzstoatzz commented on src/marvin/cli/server.py
> +    host: str = typer.Option(
let's add a default here from the marvin settings
```suggestion
    host: str = typer.Option(
        marvin.settings.api_base_url,
```

2023-06-13 13:26 UTC, jicuss commented
reformatting server.py to reflect the standards expected by pre-commit.

2023-06-16 20:14 UTC, zzstoatzz approved these changes
build docs and llm tests are failing because your PR is from a fork, so lgtm!

2023-06-16 20:15 UTC, merged