ai_model to use ChatCompletion; deprecates ChatLLM
PrefectHQ/marvin pull request #544
Opened 2023-08-24 21:34 UTC by aaazzam

ai_model to use ChatCompletion; deprecates ChatLLM

similar to ai_fn:

- exposes say, Person.prompt(text: str) to create ejectable prompts, etc. 
- adds context: Callable[str, dict] that adds dynamic context for RAG (defaults to exposing datetime.now as before)

2023-08-26 13:10 UTC, jlowin approved these changes

2023-08-26 13:11 UTC, jlowin requested changes

2023-08-26 13:11 UTC, jlowin commented on src/marvin/components/ai_function.py
> +        if asyncio.get_event_loop().is_running():
I don't think we should support this pattern of unclear sync/async methods. Map is sync and Amap is async. Prefect has to support this for mixing and matching tasks but Marvin is under no obligation to introduce confusion in return signature.

2023-08-28 17:36 UTC, zzstoatzz approved these changes

2023-08-28 18:49 UTC, jlowin approved these changes

2023-08-28 18:58 UTC, merged